// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Wed, 30 Nov 2016 06:37:19 JST.
// By https://git.io/cgogen. DO NOT EDIT.

#include "lzfse.h"
#include <stdlib.h>
#pragma once

#define __CGOGEN 1

